crops/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('csvs.urls', namespace='csvs')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

csvs/urls.py
from django.urls import path
from .views import upload_file_view, variety_profile, index, CropsDetailView

app_name='csvs'

urlpatterns = [
    path('', index, name="index"),
    path('upload', upload_file_view, name="upload-view"),
    path('variety/<id>', variety_profile, name="variety_profile"),
    path('crop/<slug>', CropsDetailView.as_view(), name="crop"),
]

crop_details/models.py
from django.db import models
from django.shortcuts import reverse

# Create your models here.product_variety = models.ManyToManyField(Product_Variety)


class Product_Variety(models.Model):
    variety = models.CharField(max_length=200)
    image = models.ImageField(blank=True, null=True)

    def __str__(self):
        return self.variety

    def get_variety_absolute_url(self):
        return reverse('csvs:variety_profile', kwargs={
            'id': self.id
        })


UNITS = (
    ('ExtBag', 'Ext Bag'),
    ('MedBunch','Med Bunch' ),
    ('LgBox','Lg Box'),
    ('Bag', 'Bag'),
    ('SmBasket', 'Sm Basket'),
    ('net', 'net'),
    ('Dozen', 'Dozen'),
    ('crate', 'crate')
)


class Crops(models.Model):
    commodity = models.CharField(max_length=100)
    product_variety = models.ManyToManyField(Product_Variety, related_name='produce_variety')
    image = models.ImageField(default='')
    unit = models.CharField(max_length=20, choices=UNITS)
    volume_in_kgs = models.PositiveIntegerField()
    values_in_ksh = models.FloatField(null=True, blank=True, default=0.0)
    date = models.TextField(blank=True, null=True)
    slug = models.SlugField()


    def __str__(self):
        return f"{self.commodity}-{self.slug}"

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('csvs:crop', kwargs={
            'slug': self.slug
        })

class Commodity_Type(models.Model):
    commodity = models.ForeignKey(Crops, on_delete=models.CASCADE)
    image = models.ImageField(blank=True, null=True)

    def __str__(self):
        return self.commodity
   

csvs/models.py
from django.db import models

# Create your models here.
class Csv(models.Model):
    file_name = models.FileField(upload_to='csvs')
    uploaded = models.DateTimeField(auto_now_add=True)
    activated = models.BooleanField(default=False)

    def __str__(self):
        return f"File id: {self.id}"

csvs/forms.py
from django import forms
from .models import Csv

class CsvModelForm(forms.ModelForm):
    class Meta:
        model = Csv
        fields = ('file_name', )

crop_details/views.py
from django.shortcuts import render

# Create your views here.

csvs/views.py
from django.db.models import Q
from django.shortcuts import render, get_object_or_404
from django.views.generic import DetailView
from .forms import CsvModelForm
from .models import Csv
import csv, ast 
from datetime import datetime
from crop_details.models import Crops, Commodity_Type, Product_Variety

# Create your views here.

def index(request):
    latest = Crops.objects.order_by('-date')
    variety = get_variety()
    all_varieties = Product_Variety.objects.all()
    crops = Crops.objects.all()

    context =  {
        'crops': crops,
        'latest': latest,
        'variety': variety,
        'all_varieties': all_varieties,
        }

    return render(request, 'csvs/home.html',context)


class CropsDetailView(DetailView):
    model = Crops
    template_name = "csvs/crop.html"


def get_variety():
    queryset = Crops.objects.values('product_variety__variety')
    return queryset


def upload_file_view(request):
    form = CsvModelForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        form.save()
        form = CsvModelForm()
        obj = Csv.objects.get(activated=False)
        with open(obj.file_name.path, 'r') as f:
            reader = csv.reader(f)
            for i, row in enumerate(reader):
                # try: 
                    if i==0:
                        pass
                    else:
                        # row = "".join(row)
                        # row = row.replace(" ", "")
                        # row = row.split()
                        # print(row)
                        # # print(type(row))
                        commodity = row[1]
                        unit = row[2]
                        volume_in_kgs = row[3]
                        values_in_ksh = row[4]
                        date = datetime.strptime(row[5], '%m/%d/%Y %H:%M')
                        slug = row[6]
                        instance = Crops.objects.create(
                            # product_variety = product_variety,
                            commodity = commodity,
                            unit = unit,
                            volume_in_kgs = volume_in_kgs,
                            values_in_ksh = values_in_ksh,
                            date = date,
                            slug = slug
                        )
                        instance.save()
                        product_variety = Product_Variety.objects.filter(variety=row[0])
                        for var in product_variety:
                            instance.product_variety.add(var)
                        # commodity_type = Commodity_Type.objects.filter(commodity_type=row[1])
                        # for comm in commodity_type:
                        #     instance.commodity_type.add(comm)
                            
                        print(instance)
                #         crops, _ = Crops.objects.get_or_create(
                #             commodity_type = row[1],
                #             unit = row[2],
                #             volume_in_kgs = row[3],
                #             values_in_ksh = row[4],
                #             date = datetime.strptime(row[5], '%m/%d/%Y %H:%M'),
                #         )
                #         varieties_str = row[0]
                #         variety_names = ast.literal_eval(varieties_str)
                #         variety_names = map(str.lower, variety_names)
                #         variety_names = list(set(variety_names))
                #         for variety_name in variety_names:
                #             var, _ = Product_Variety.objects.get_or_create(variety=variety_name)
                #             crops.product_variety.add(var)
                # except Exception as e:
                #     print(e)
            obj.activated = True
            obj.save()

    context =  {
        'form': form,
        }
            
    return render(request, 'csvs/upload.html',context)

def variety_profile(request, id):
    one_variety = get_object_or_404(Product_Variety, id=id)
    var_queryset = Crops.objects.all()
    var_query = one_variety.variety
    var_queryset = var_queryset.filter(Q(product_variety__variety__icontains=var_query)).distinct()
    
    context = {
        'one_variety': one_variety,
        'queryset': var_queryset,
    }

    return render(request, "csvs/variety_profile.html", context)

csvs/templates/csvs/crop.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
        <div>
            
        </div>
        <div>
            <h5>{{ object.commodity }}</h5>
            {% for var in  object.product_variety.all %}
            <h5>{{ var }}</h5>
            {% endfor %}
            <h5>{{ object.values_in_ksh }}</h5>
            <h5>{{ object.volume_in_kgs }}</h5>
            
        </div>
        <div class="row my-4">
            <div class="col-md-1">
            </div>
            <div class="col-md-10">
                
            </div>
            <div class="col-md-1">
            </div>
        </div>

           
    </div>

 
                                  
                            
                                
                                
                       
                    
              

    {% endblock content %}

csvs/templates/csvs/home.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}
    Main Page

{% endblock title %}

{% block content %}
<head>
  
</head>
<body>

{% include "topside.html" %}

{% comment %} backgroundColor: '#' + Math.floor(Math.random()*16777215).toString(16) {% endcomment %}

 
<div class="container">
        <div class="row my-4">
            <div class="col-md-1">
            </div>
            <div class="col-md-10">
                <div class="scrollable">
                    <table class="table bg-white">
                        <thead class="bg-info">
                            <tr class="text-white">
                                <th scope="col">ID </th>
                                <th scope="col">Commodity Type </th>
                                <th scope="col">Product Variety</th>
                                <th scope="col">Unit</th>
                                <th scope="col">Volume in Kgs</th>
                                <th scope="col">Values in Ksh</th>
                                <th scope="col">Date</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in latest %}
                            <tr>
                                <td>{{ item.slug }}</td>
                                <td><a href="{{ item.get_absolute_url }}">{{ item.commodity }}</a></td>
                                {% for var in item.product_variety.all %}
                                <td>{{ var.variety }}</td>
                                {% endfor %}
                                <td>{{ item.unit }}</td>
                                
                                <td>{{ item.volume_in_kgs }}</td>
                                <td>{{ item.values_in_ksh }}</td>
                                <td>{{ item.date }}</td>
                                
                            </tr>
                            {% endfor %}
                        
                            
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="col-md-1">
            </div>
        </div>

           
    </div>



</body>
{% endblock content %}

csvs/templates/csvs/upload.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}
    Main Page

{% endblock title %}

{% block content %}
<head>
  

</head>
<body>

<div class="container">
        <div class="row my-4">
            <div class="col-md-3">
            </div>
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header bg-info text-white">
                       Upload CSV File here
                    </div>
                    <div class="card-body">
                        <div class="border bg-white p-3">
                            <h4>Add csv</h4>
                            <hr>
                            <form method="POST", enctype="multipart/form-data" >
                                {% csrf_token %}
                                {{ form|crispy }}
                                <input class="btn btn-success btn-block" type="submit" value="Add CSV">
                            </form>
                    </div>

                       
                    </div>
                </div>
            </div>
            <div class="col-md-3">
            </div>
        </div>

           
    </div>
</body>
{% endblock content %}

{% comment %} backgroundColor: '#' + Math.floor(Math.random()*16777215).toString(16) {% endcomment %}

csvs/templates/csvs/variety_profile.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
        <div>
            <h5>{{ one_variety.variety }}</h5>
        </div>
        <div class="row my-4">
            <div class="col-md-1">
            </div>
            <div class="col-md-10">
                <div class="scrollable">
                    <table class="table bg-white">
                        <thead class="bg-info">
                            <tr class="text-white">
                                <th scope="col">ID</th>
                                <th scope="col">Commodity Type</th>
                                <th scope="col">Unit</th>
                                <th scope="col">Volume in Kgs</th>
                                <th scope="col">Values in Ksh</th>
                                <th scope="col">Date</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for var in queryset %}
                            <tr>
                                <td>{{ var.slug }}</td>
                                <td>{{ var.commodity }}</td>
                                
                                <td>{{ var.unit }}</td>
                                
                                <td>{{ var.volume_in_kgs }}</td>
                                <td>{{ var.values_in_ksh }}</td>
                                <td>{{ var.date }}</td>
                                
                            </tr>
                            {% endfor %}
                        
                            
                        </tbody>
                    </table> 
                </div>
            </div>
            <div class="col-md-1">
            </div>
        </div>

           
</div>

<div class="container">
        <div class="row my-5">
            
            <div class="col-md-12">
            <div class="bg-white">
                <canvas id="myChart" width="400" height="300"></canvas>
                <script>
                var ctx = document.getElementById('myChart').getContext('2d');
                var myChart = new Chart(ctx, {
                    type: 'bar',
                    data: {
                        labels: [{% for var in queryset %} '{{ var.commodity }}', {% endfor %}],
                        datasets: [{
                            label: 'Crops',
                            data: [{% for var in queryset %} {{ var.values_in_ksh }}, {% endfor %}],
                            backgroundColor: [
                                'rgba(255, 99, 132, 1)',
                                'rgba(54, 162, 235, 1)',
                                'rgba(255, 206, 86, 1)',
                                'rgba(75, 192, 192, 1)',
                                'rgba(153, 102, 255, 1)',
                                'rgba(255, 159, 64, 1)'
                            ],
                            borderColor: [
                                'rgba(255, 99, 132, 1)',
                                'rgba(54, 162, 235, 1)',
                                'rgba(255, 206, 86, 1)',
                                'rgba(75, 192, 192, 1)',
                                'rgba(153, 102, 255, 1)',
                                'rgba(255, 159, 64, 1)'
                            ],
                            borderWidth: 1
                        }]
                    },
                    options: {
                        scales: {
                            y: {
                                beginAtZero: true
                            }
                        }
                    }
                });
                </script>
            </div>
            </div>
            
        </div>
    </div>

 
{% endblock content %}

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
   <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    
    <!-- Font Awesome CDN -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">
    
    <!--Chartjs-->
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.4.0/dist/chart.min.js"></script>
     
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
  
    <title>{% block head_title %} {% endblock %}</title>
    
    
  </head>
  <body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    {% include "navbar.html" %}

    <div class="container">
      {% block content %}
      {% endblock content %}
    </div>
    
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

   
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
  </body>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-info bg-info">
       
        <div class="container">
            <a class="navbar-brand text-white" href="{% url 'csvs:index' %}">MishqaInventory</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link text-white" href="{% url 'csvs:index' %}">Dashboard<span class="sr-only">(current)</span></a>
                    </li>
                   
                </ul>
                 <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url 'csvs:upload-view' %}">Upload Csv</a>
                    </li>
                    
                </ul>
            </div>
        </div>
        
</nav>

templates/topside.html
{% load crispy_forms_tags %}



<div class="container">
        <div class="row mt-4">
            
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header bg-info text-white">
                        Product Variety
                    </div>
                    <div class="card-body">
                        <div class="row">
                            {% for var in all_varieties %}
                            <div class="col-md-3 p-2">
                                <a class="text-decoration-none text-dark" href="">
                                    <div class="card my-card shadow text-center p-3">
                                        <h4><i class="fas fa-users"></i></h4>
                                        
                                        <a  href="{{ var.get_variety_absolute_url }}" class="card-body"><h3>{{ var }}</h3> </a>
                                    </div>
                                </a>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>